const sidebars = {
  // Sidebar for /docs/api section (autogenerated from docs/api/)
  apiSidebar: [{ type: 'autogenerated', dirName: 'api' }], // This will include everything under docs/api/

  // Sidebar for /docs/api-v2 section (autogenerated from docs/api-v2/)
  apiV2Sidebar: [{ type: 'autogenerated', dirName: 'api-v2' }], // This will include everything under docs/api-v2/
};

module.exports = sidebars;
