const sidebars = {
  // Sidebar for /docs/api section (autogenerated from docs/api/)
  apiSidebar: [
    {
      type: 'category',
      label: 'API v1 Documentation',
      collapsed: true, // Ensure folders remain collapsed
      items: [{ type: 'autogenerated', dirName: 'api' }],
    },
  ],

  // Sidebar for /docs/api-v2 section (autogenerated from docs/api-v2/)
  apiV2Sidebar: [
    {
      type: 'category',
      label: 'API v2 Documentation',
      collapsed: true, // Ensure folders remain collapsed
      items: [{ type: 'autogenerated', dirName: 'api-v2' }],
    },
  ],
};

module.exports = sidebars;
