/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
// const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // docsSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
// };

const sidebars = {
  // Sidebar for /docs/api section (autogenerated from docs/api/)
  apiSidebar: [
    {
      type: 'category',
      label: 'Introduction', // This is the category for the Introduction
      items: [
        'api-v2/index',  // Corresponds to docs/api-v2/index.md
        'api-v2/authentication',  // Add the authentication.md as part of Introduction
      ],
    },
    // Other categories (if any)
  ],

  // Sidebar for /docs/api-v2 section (manually defined)
  apiV2Sidebar: [
    {
      type: 'category',
      label: 'API Version 2 Documentation',
      items: [
        'api-v2/index',  // Main entry for /docs/api-v2
        'api-v2/authentication',  // Main entry for /docs/api-v2
        'api-v2/request-flow',  // Main entry for /docs/api-v2
        'api-v2/encryption-security',  // Main entry for /docs/api-v2
        'api-v2/contact-support',  // Main entry for /docs/api-v2
        {
          type: 'category',
          label: 'API Endpoints',  // This groups API endpoints under "Endpoints"
          collapsed: false,  // Set to true if you want it to be collapsible
          items: [
            'api-v2/api-endpoints/payin',  // Payin file inside Endpoints
            'api-v2/api-endpoints/payout',  // Payin file inside Endpoints
            'api-v2/api-endpoints/fetch-transaction-status',  // Payin file inside Endpoints
            'api-v2/api-endpoints/fetch-payout-status',  // Payin file inside Endpoints
            'api-v2/api-endpoints/check-payout-balance',  // Payin file inside Endpoints
          ],
        },  // Main entry for /docs/api-v2
      ],
    },
  ],
};

module.exports = sidebars;
